apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
spec:
  selector:
    matchLabels:
      app: nextjs-app
  replicas: 2
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
      - name: nextjs-app
        image: yumekiti/nextjs-app:latest
        # image: nextjs-app:latest
        ports:
        - containerPort: 3000
